// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IProjectsFields {
  /** Title */
  title: string;

  /** Image */
  image: Asset;

  /** Description */
  description: string;

  /** Tags */
  tags: string[];

  /** Repository Link */
  repositoryLink?: string | undefined;

  /** Live-view Link */
  liveViewLink?: string | undefined;
}

export interface IProjects extends Entry<IProjectsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "projects";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "projects";

export type IEntry = IProjects;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
